JWT_SECRET = "PHARM1234!"
JWT_ALGORITHM = "HS256"
# EXCEPT_PATH_LIST = ["/", "/login/", "/logout/"]
EXCEPT_PATH_LIST = ["/", "/login/"]
EXCEPT_PATH_REGEX = "^(/docs|/redoc|/static/)"
# EXCEPT_PATH_REGEX = "^(/docs|/redoc|/api/auth|/static/|/api/login/)"
MAX_API_KEY = 3
MAX_API_WHITELIST = 10
ACCESS_TOKEN_EXPIRE_MINUTES = 300  # in mins
